minimum_pre_commit_version: 4.0.0
exclude: ^LICENSES/|\.(html|csv|svg|ini)$
default_stages: [
    pre-commit,
    pre-merge-commit,
    pre-push,
    prepare-commit-msg,
    commit-msg,
    post-checkout,
    post-commit,
    post-merge,
    post-rewrite
]
ci:
    # autofix_prs: false
    autoupdate_schedule: monthly
repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.4
    hooks:
    -   id: ruff
        name: ruff
        args: [ --fix ]
        exclude: ^samples/
    -   id: ruff-format
        # TODO: remove autofix only rules when they are checked by ruff
        name: ruff-format
        files: ^src/
        exclude: ^samples/
-   repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
    -   id: codespell
        types_or: [python, rst, markdown, cython, c]
        additional_dependencies: [tomli]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: trailing-whitespace
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
    -   id: pyupgrade
        args: [--py311-plus]
